# ==============================
# 基本配置
# ==============================
title: xxxkChow 的个人博客
description: 欢迎来到我的技术和生活分享空间。
baseurl: ""
url: "https://Unconnectable.github.io"
author: xxxkChow

# ==============================
# 集合配置 (核心修改)
# ==============================
collections:
  articles:
    output: true # 必须设置为 true，Jekyll 才会为该集合中的文件生成页面
    permalink: /articles/:name/ # 设置 URL 格式：/articles/1/，/articles/2/ 等

# ==============================
# 默认设置
# ==============================
markdown: kramdown

# 指定 _articles 集合中的文件默认使用 article 布局
defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
